# Generated by Django 5.0 on 2024-02-22 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e6347cde-9ba2-4c74-8869-5ce95828d4d2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
