# Generated by Django 5.0.2 on 2024-02-22 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='retweet',
        ),
        migrations.RemoveField(
            model_name='post',
            name='save',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0784fdc7-00f8-4f43-be2c-5d9173fc64c9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
