# Generated by Django 5.0.2 on 2024-02-22 17:06

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_save_alter_post_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('695c8e10-47e8-4347-9ed8-c91f0544167f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Beğenenler'),
        ),
        migrations.AlterField(
            model_name='post',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='saves', to=settings.AUTH_USER_MODEL, verbose_name='Kaydedenler'),
        ),
    ]
