# Generated by Django 5.0.2 on 2024-02-22 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_id_alter_post_like_alter_post_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='save',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0e5cfb01-cf30-456d-87d0-5004d8fd66a0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
