# Generated by Django 5.0.2 on 2024-02-22 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_save_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('97d08d2b-3d3f-4aa5-b29c-fc348a320586'), editable=False, primary_key=True, serialize=False),
        ),
    ]
