# Generated by Django 5.0.2 on 2024-02-22 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('23c5369b-62c7-47b8-9fea-85a11993fff0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
