# Generated by Django 5.0.2 on 2024-02-22 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('746a4309-8d14-4426-8fb0-6bffb2d08b89'), editable=False, primary_key=True, serialize=False),
        ),
    ]
