# Generated by Django 5.0.2 on 2024-02-22 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='saves',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('94b13ddd-c9f3-4464-957d-fe9820e02e88'), editable=False, primary_key=True, serialize=False),
        ),
    ]
