# Generated by Django 5.0.2 on 2024-02-22 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_rename_save_post_saves_alter_post_id'),
        ('user', '0018_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='retweet',
            field=models.ManyToManyField(blank=True, related_name='retweet', to='user.profile', verbose_name='Retweet'),
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='views', to='user.profile', verbose_name='Görüntüleyenler'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('43e4e78c-45a9-4bb0-b1c7-e54a178152df'), editable=False, primary_key=True, serialize=False),
        ),
    ]
