# Generated by Django 5.0.2 on 2024-02-22 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_retweet_post_view_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0300c5eb-b070-4740-adb2-a27c6b50cde5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
