# Generated by Django 5.0.2 on 2024-02-22 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a233cec7-e271-4c95-a62a-c445c75f2394'), editable=False, primary_key=True, serialize=False),
        ),
    ]
