# Generated by Django 5.0.2 on 2024-02-22 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('9fbc6051-86ca-41e4-871f-8a63c1274e4e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
