# Generated by Django 5.0.2 on 2024-02-22 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('1d6c6773-1548-4117-8d3f-ed1a464a0f33'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
