# Generated by Django 5.0.2 on 2024-02-22 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('64f89fe9-1356-4b75-ba69-a7ab464c0dae'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
