# Generated by Django 5.0.2 on 2024-02-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_comment'),
        ('user', '0028_alter_profile_follow_alter_profile_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('begeni', 'Beğenme'), ('retweet', 'Retweet'), ('kaydetme', 'Kaydetme'), ('takip', 'Takip'), ('yorum', 'Yorum')], max_length=50, verbose_name='İşlem')),
                ('isRead', models.BooleanField(default=False, verbose_name='Okundu Bilgisi')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='İşlem yapılan Post')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Bildirim Alan')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to='user.profile', verbose_name='Bildirim Gönderen')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
            },
        ),
    ]
