# Generated by Django 5.0.2 on 2024-02-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_notificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
