# Generated by Django 5.0.2 on 2024-02-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_notificate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificate',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='İşlem yapılan Post'),
        ),
    ]
