# Generated by Django 5.0 on 2024-02-20 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('2a427af6-4b29-40e0-9b70-22d3ec75bd98'), editable=False, primary_key=True, serialize=False),
        ),
    ]
