# Generated by Django 5.0 on 2024-02-22 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('4b3dd933-7738-4479-a1b1-6b23ccecf964'), editable=False, primary_key=True, serialize=False),
        ),
    ]
