# Generated by Django 5.0.2 on 2024-02-22 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('1ead009d-e630-4749-a084-90a6be913fde'), editable=False, primary_key=True, serialize=False),
        ),
    ]
