# Generated by Django 5.0.2 on 2024-02-22 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('45209898-24b0-4295-930e-23d38f4a135e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
