# Generated by Django 5.0.2 on 2024-02-22 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e9fe6431-d544-4fcc-90e2-1aa80d180c99'), editable=False, primary_key=True, serialize=False),
        ),
    ]
