# Generated by Django 5.0.2 on 2024-02-22 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6654f1be-8b9f-4cc9-bdea-321a75ba4ad7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
