# Generated by Django 5.0.2 on 2024-02-22 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('7420c544-60a6-4627-bf84-e9abe7942654'), editable=False, primary_key=True, serialize=False),
        ),
    ]
