# Generated by Django 5.0.2 on 2024-02-22 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('ac6df383-34d2-452d-8b92-fb64a8bfb76b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
