# Generated by Django 5.0.2 on 2024-02-22 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('2dd6967f-bc5e-4e29-b7ed-56929e6bc54f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
