# Generated by Django 5.0.2 on 2024-02-22 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('efd33619-4f4a-4075-b17f-82f7a7c79a39'), editable=False, primary_key=True, serialize=False),
        ),
    ]
