# Generated by Django 5.0.2 on 2024-02-22 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39ed5c14-c8e5-4b0c-a213-d4c635263617'), editable=False, primary_key=True, serialize=False),
        ),
    ]
