# Generated by Django 5.0.2 on 2024-02-22 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0776b7bc-8df1-485b-8eab-f606b8b49581'), editable=False, primary_key=True, serialize=False),
        ),
    ]
