# Generated by Django 5.0.2 on 2024-02-22 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20f3acb1-329b-4ff4-ba70-ac48307a9394'), editable=False, primary_key=True, serialize=False),
        ),
    ]
