# Generated by Django 5.0.2 on 2024-02-22 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0e55fde6-397e-4d41-a12c-7246b45cc433'), editable=False, primary_key=True, serialize=False),
        ),
    ]
