# Generated by Django 5.0.2 on 2024-02-22 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c98dbdb0-f51d-41f2-ba82-defb5cc9da55'), editable=False, primary_key=True, serialize=False),
        ),
    ]
