# Generated by Django 5.0.2 on 2024-02-22 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0d8ec9ae-7d79-4449-ac78-589afe5693c7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
