# Generated by Django 5.0.2 on 2024-02-22 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0dbee584-7f2b-4aef-8c02-c7de628b0e49'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
