# Generated by Django 5.0.2 on 2024-02-22 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('9c8bd1d2-2ead-4260-8ff5-998e68e945e1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
